### ISSUE TITLE
Set Clock in example.py

### ISSUE THREAD

**Issue by elitechdatareader** [civic/elitech-datareader#14]
example.py causes a struct.error when run under Linux (and possibly other operating systems):

`Traceback (most recent call last):
  File "example.py", line 16, in <module>
    device.set_clock(datetime.datetime.now())
  File "~/elitech-datareader-master/elitech/__init__.py", line 185, in set_clock
    self._talk(req, res)
  File "~/elitech-datareader-master/elitech/__init__.py", line 52, in _talk
    ba = request.to_bytes()
  File "~/elitech-datareader-master/elitech/msg.py", line 440, in to_bytes
    _datetime_pack(self.set_time),
struct.error: cannot convert argument to integer`

The error is due to this line in example.py:

device.set_clock(datetime.datetime.now())

**Comment by civic** [comment]
thank you for your report. I fixed.
https://github.com/civic/elitech-datareader/commit/bef04cfe277073e8bed0bc0c01152bace8799f31

**Comment by elitechdatareader** [comment]
I can confirm it is fixed for me too!
