### ISSUE TITLE
"year is out of range" error

### ISSUE THREAD

**Issue by kobayashison** [civic/elitech-datareader#2]
I just bought one RC-4 and at the first try:
```
$ ./elitech-device.py --command simple-set --interval=10 /dev/ttyUSB0 
Traceback (most recent call last):
  File "./elitech-device.py", line 147, in <module>
    main()
  File "./elitech-device.py", line 17, in main
    command_simpleset(args)
  File "./elitech-device.py", line 36, in command_simpleset
    dev_info = device.get_devinfo()
  File "/home/paolo/.local/lib/python2.7/site-packages/elitech/__init__.py", line 93, in get_devinfo
    res = self._talk(req, DevInfoResponse())
  File "/home/paolo/.local/lib/python2.7/site-packages/elitech/__init__.py", line 67, in _talk
    response.read(self._ser)
  File "/home/paolo/.local/lib/python2.7/site-packages/elitech/msg.py", line 208, in read
    self.start_time = _datetime_unpack(start_time)
  File "/home/paolo/.local/lib/python2.7/site-packages/elitech/msg.py", line 30, in _datetime_unpack
    return datetime(*unpack(">h5b", date_bytes))
ValueError: year is out of range
```

**Comment by kobayashison** [comment]
I confirm that after initializing the device with the Elitech Windows application, I can use elitech-datareader. I still have a virgin device, if you want me to do some tests to resolve this issue.

**Comment by civic** [comment]
Thanks, I'll check it.

**Comment by civic** [comment]
I've update v0.9.1. Please check it on a virgin device.

**Comment by kobayashison** [comment]
Thank you, it works!
OT: check mistypes in readme.md, especially the parameters in the examples and elitec-datareader instead of elitech-datareader in many points.
